# Generated by Django 4.0.6 on 2022-07-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comics_prev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_image', models.TextField(db_column='path_image')),
                ('comics_t', models.CharField(db_column='title', max_length=50)),
                ('comics_amount', models.IntegerField(db_column='comics_amount')),
            ],
            options={
                'db_table': 'comics',
            },
        ),
    ]
